server:
  port: 8080

#test-propertiy:
#  id: admin01
#  password: abc123
#
HOME:
  URL: http://localhost:8080/login

car:
  name: hyundai

# 카카오 로그인 API
Kakao:
  client_id: cc55a9f1d718f1adfc4786e46a20f00c
  grant_type: authorization_code

  access_token: https://kauth.kakao.com/oauth/token
  user_info: https://kapi.kakao.com/v2/user/me
  logout: https://kapi.kakao.com/v1/user/logout
  disconnect: https://kapi.kakao.com/v1/user/unlink
  redirect_uri: http://localhost:8080/login


spring:
  # https://www.inflearn.com/questions/230160
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  # 자동 reload
  devtools:
    livereload:
      enabled: true

  # DB 설정
  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db_padak?serverTimezone=UTC&characterEncoding=UTF-8

  # Security (아직 안씀)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: #<your id>
            client-secret: #<your secret>
            redirect-uri: http://localhost:8080/login #<your url>/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  #  file:
  #    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
  #    max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
  #    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.

  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.fish.encyclopedia : error
    com.fish.encyclopedia.OAuth2.controller : debug

    com.project.study : error
    com.project.study.controller : debug

    org:
      hibernate:
        SQL: DEBUG
        type:
          trace
